name: Terraform Module Releaser (Test)

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main  

permissions:
  contents: write # Required for to push tags, create release, and push changes to the wiki 
  pull-requests: write # Required to comment on pull request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Terraform Module Releaser (Test Mode)
        uses: techpivot/terraform-module-releaser@v1
        with:
          major-keywords: major update,breaking change
          minor-keywords: feat,feature
          patch-keywords: fix,chore,docs
          default-first-tag: v0.1.0
          use-version-prefix: true
          tag-directory-separator: /

          module-path-ignore: examples/**,scripts/**,test/**,.github/**
          module-change-exclude-patterns: .gitignore,*.md,docs/**,examples/**,*.tftest.hcl,tests/**
          module-asset-exclude-patterns: .gitignore,*.md,*.tftest.hcl,tests/**
          use-ssh-source-format: true
          module-ref-mode: tag

          disable-wiki: false
          terraform-docs-version: v0.20.0

          delete-legacy-tags: true
          wiki-sidebar-changelog-max: 10

          wiki-usage-template: |
            **Test Mode**

            The following variables are supported:
            - {{module_name}}
            - {{latest_tag}}
            - {{latest_tag_version_number}}
            - {{ref}}
            - {{ref_comment}}
            - {{module_source}}
            - {{module_name_terraform}}

            ```hcl
            module "{{module_name_terraform}}" {
              source = "{{module_source}}?ref={{ref}}"{{ref_comment}}
            }
            ```

