name: Terraform Module Releaser
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, closed] # Closed required
    branches:
      - main

permissions:
  contents: write # Required for to push tags, create release, and push changes to the wiki
  pull-requests: write # Required to comment on pull request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 

      - name: Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v1
        with:
          major-keywords: major update,breaking change
          minor-keywords: feat,feature
          patch-keywords: fix,chore,docs
          default-first-tag: v1.0.0
          terraform-docs-version: v0.20.0
          delete-legacy-tags: true
          disable-wiki: false
          wiki-sidebar-changelog-max: 10
          module-path-ignore: "**/examples,**/examples/**,scripts/**,test/**,.github/**"
          module-change-exclude-patterns: '.gitignore,*.md,docs/**,examples/**,*.tftest.hcl,tests/**'
          module-asset-exclude-patterns: '.gitignore,*.md,*.tftest.hcl,tests/**'
          use-ssh-source-format: true
          tag-directory-separator: /
          use-version-prefix: true
          module-ref-mode: tag
          wiki-usage-template: |
            This is a custom wiki usage block that supports markdown.

            The following variables are supported:
            - {{module_name}}
            - {{latest_tag}}
            - {{latest_tag_version_number}}
            - {{ref}}
            - {{ref_comment}}
            - {{module_source}}
            - {{module_name_terraform}}

            ```hcl
            module "{{module_name_terraform}}" {
              source = "{{module_source}}?ref={{ref}}"{{ref_comment}}

              # See inputs below for additional required parameters
            }
            ```
